# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weekdays = QtWidgets.QHBoxLayout()
        self.weekdays.setObjectName("weekdays")
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.weekdays.addItem(spacerItem)
        self.verticalLayout.addLayout(self.weekdays)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.take_in = QtWidgets.QLabel(self.centralwidget)
        self.take_in.setMinimumSize(QtCore.QSize(175, 200))
        self.take_in.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(18)
        self.take_in.setFont(font)
        self.take_in.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.take_in.setObjectName("take_in")
        self.horizontalLayout_2.addWidget(self.take_in)
        self.take_out = QtWidgets.QLabel(self.centralwidget)
        self.take_out.setMinimumSize(QtCore.QSize(175, 0))
        self.take_out.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(18)
        self.take_out.setFont(font)
        self.take_out.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.take_out.setObjectName("take_out")
        self.horizontalLayout_2.addWidget(self.take_out)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.take_in.setText(_translate("MainWindow", "Take in"))
        self.take_out.setText(_translate("MainWindow", "Take out"))
