# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weekday.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 371)
        Form.setMinimumSize(QtCore.QSize(173, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        self.label.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.class_1 = QtWidgets.QComboBox(Form)
        self.class_1.setMinimumSize(QtCore.QSize(80, 22))
        self.class_1.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_1.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_1.setObjectName("class_1")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.class_1.addItem("")
        self.verticalLayout.addWidget(self.class_1)
        self.class_2 = QtWidgets.QComboBox(Form)
        self.class_2.setMinimumSize(QtCore.QSize(80, 22))
        self.class_2.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_2.setObjectName("class_2")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.verticalLayout.addWidget(self.class_2)
        self.class_3 = QtWidgets.QComboBox(Form)
        self.class_3.setMinimumSize(QtCore.QSize(80, 22))
        self.class_3.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_3.setObjectName("class_3")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.class_3.addItem("")
        self.verticalLayout.addWidget(self.class_3)
        self.class_4 = QtWidgets.QComboBox(Form)
        self.class_4.setMinimumSize(QtCore.QSize(80, 22))
        self.class_4.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_4.setObjectName("class_4")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.class_4.addItem("")
        self.verticalLayout.addWidget(self.class_4)
        self.class_5 = QtWidgets.QComboBox(Form)
        self.class_5.setMinimumSize(QtCore.QSize(80, 22))
        self.class_5.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_5.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_5.setObjectName("class_5")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.class_5.addItem("")
        self.verticalLayout.addWidget(self.class_5)
        self.class_6 = QtWidgets.QComboBox(Form)
        self.class_6.setMinimumSize(QtCore.QSize(80, 22))
        self.class_6.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_6.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_6.setObjectName("class_6")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.class_6.addItem("")
        self.verticalLayout.addWidget(self.class_6)
        self.class_7 = QtWidgets.QComboBox(Form)
        self.class_7.setMinimumSize(QtCore.QSize(80, 22))
        self.class_7.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_7.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_7.setObjectName("class_7")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.class_7.addItem("")
        self.verticalLayout.addWidget(self.class_7)
        self.class_8 = QtWidgets.QComboBox(Form)
        self.class_8.setMinimumSize(QtCore.QSize(80, 22))
        self.class_8.setMaximumSize(QtCore.QSize(11111, 16777215))
        self.class_8.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color: #d1d1d1\n"
"}\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px\n"
"}\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}")
        self.class_8.setObjectName("class_8")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.class_8.addItem("")
        self.verticalLayout.addWidget(self.class_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Wednesday"))
        self.class_1.setItemText(0, _translate("Form", "-"))
        self.class_1.setItemText(1, _translate("Form", "Алгебра"))
        self.class_1.setItemText(2, _translate("Form", "Английский язык"))
        self.class_1.setItemText(3, _translate("Form", "Биология"))
        self.class_1.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_1.setItemText(5, _translate("Form", "География"))
        self.class_1.setItemText(6, _translate("Form", "Геометрия"))
        self.class_1.setItemText(7, _translate("Form", "Информатика"))
        self.class_1.setItemText(8, _translate("Form", "История"))
        self.class_1.setItemText(9, _translate("Form", "Литература"))
        self.class_1.setItemText(10, _translate("Form", "Обществознание"))
        self.class_1.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_1.setItemText(12, _translate("Form", "Русский язык"))
        self.class_1.setItemText(13, _translate("Form", "Технология"))
        self.class_1.setItemText(14, _translate("Form", "Физика"))
        self.class_1.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_1.setItemText(16, _translate("Form", "Химия"))
        self.class_2.setItemText(0, _translate("Form", "-"))
        self.class_2.setItemText(1, _translate("Form", "Алгебра"))
        self.class_2.setItemText(2, _translate("Form", "Английский язык"))
        self.class_2.setItemText(3, _translate("Form", "Биология"))
        self.class_2.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_2.setItemText(5, _translate("Form", "География"))
        self.class_2.setItemText(6, _translate("Form", "Геометрия"))
        self.class_2.setItemText(7, _translate("Form", "Информатика"))
        self.class_2.setItemText(8, _translate("Form", "История"))
        self.class_2.setItemText(9, _translate("Form", "Литература"))
        self.class_2.setItemText(10, _translate("Form", "Обществознание"))
        self.class_2.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_2.setItemText(12, _translate("Form", "Русский язык"))
        self.class_2.setItemText(13, _translate("Form", "Технология"))
        self.class_2.setItemText(14, _translate("Form", "Физика"))
        self.class_2.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_2.setItemText(16, _translate("Form", "Химия"))
        self.class_3.setItemText(0, _translate("Form", "-"))
        self.class_3.setItemText(1, _translate("Form", "Алгебра"))
        self.class_3.setItemText(2, _translate("Form", "Английский язык"))
        self.class_3.setItemText(3, _translate("Form", "Биология"))
        self.class_3.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_3.setItemText(5, _translate("Form", "География"))
        self.class_3.setItemText(6, _translate("Form", "Геометрия"))
        self.class_3.setItemText(7, _translate("Form", "Информатика"))
        self.class_3.setItemText(8, _translate("Form", "История"))
        self.class_3.setItemText(9, _translate("Form", "Литература"))
        self.class_3.setItemText(10, _translate("Form", "Обществознание"))
        self.class_3.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_3.setItemText(12, _translate("Form", "Русский язык"))
        self.class_3.setItemText(13, _translate("Form", "Технология"))
        self.class_3.setItemText(14, _translate("Form", "Физика"))
        self.class_3.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_3.setItemText(16, _translate("Form", "Химия"))
        self.class_4.setItemText(0, _translate("Form", "-"))
        self.class_4.setItemText(1, _translate("Form", "Алгебра"))
        self.class_4.setItemText(2, _translate("Form", "Английский язык"))
        self.class_4.setItemText(3, _translate("Form", "Биология"))
        self.class_4.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_4.setItemText(5, _translate("Form", "География"))
        self.class_4.setItemText(6, _translate("Form", "Геометрия"))
        self.class_4.setItemText(7, _translate("Form", "Информатика"))
        self.class_4.setItemText(8, _translate("Form", "История"))
        self.class_4.setItemText(9, _translate("Form", "Литература"))
        self.class_4.setItemText(10, _translate("Form", "Обществознание"))
        self.class_4.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_4.setItemText(12, _translate("Form", "Русский язык"))
        self.class_4.setItemText(13, _translate("Form", "Технология"))
        self.class_4.setItemText(14, _translate("Form", "Физика"))
        self.class_4.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_4.setItemText(16, _translate("Form", "Химия"))
        self.class_5.setItemText(0, _translate("Form", "-"))
        self.class_5.setItemText(1, _translate("Form", "Алгебра"))
        self.class_5.setItemText(2, _translate("Form", "Английский язык"))
        self.class_5.setItemText(3, _translate("Form", "Биология"))
        self.class_5.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_5.setItemText(5, _translate("Form", "География"))
        self.class_5.setItemText(6, _translate("Form", "Геометрия"))
        self.class_5.setItemText(7, _translate("Form", "Информатика"))
        self.class_5.setItemText(8, _translate("Form", "История"))
        self.class_5.setItemText(9, _translate("Form", "Литература"))
        self.class_5.setItemText(10, _translate("Form", "Обществознание"))
        self.class_5.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_5.setItemText(12, _translate("Form", "Русский язык"))
        self.class_5.setItemText(13, _translate("Form", "Технология"))
        self.class_5.setItemText(14, _translate("Form", "Физика"))
        self.class_5.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_5.setItemText(16, _translate("Form", "Химия"))
        self.class_6.setItemText(0, _translate("Form", "-"))
        self.class_6.setItemText(1, _translate("Form", "Алгебра"))
        self.class_6.setItemText(2, _translate("Form", "Английский язык"))
        self.class_6.setItemText(3, _translate("Form", "Биология"))
        self.class_6.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_6.setItemText(5, _translate("Form", "География"))
        self.class_6.setItemText(6, _translate("Form", "Геометрия"))
        self.class_6.setItemText(7, _translate("Form", "Информатика"))
        self.class_6.setItemText(8, _translate("Form", "История"))
        self.class_6.setItemText(9, _translate("Form", "Литература"))
        self.class_6.setItemText(10, _translate("Form", "Обществознание"))
        self.class_6.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_6.setItemText(12, _translate("Form", "Русский язык"))
        self.class_6.setItemText(13, _translate("Form", "Технология"))
        self.class_6.setItemText(14, _translate("Form", "Физика"))
        self.class_6.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_6.setItemText(16, _translate("Form", "Химия"))
        self.class_7.setItemText(0, _translate("Form", "-"))
        self.class_7.setItemText(1, _translate("Form", "Алгебра"))
        self.class_7.setItemText(2, _translate("Form", "Английский язык"))
        self.class_7.setItemText(3, _translate("Form", "Биология"))
        self.class_7.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_7.setItemText(5, _translate("Form", "География"))
        self.class_7.setItemText(6, _translate("Form", "Геометрия"))
        self.class_7.setItemText(7, _translate("Form", "Информатика"))
        self.class_7.setItemText(8, _translate("Form", "История"))
        self.class_7.setItemText(9, _translate("Form", "Литература"))
        self.class_7.setItemText(10, _translate("Form", "Обществознание"))
        self.class_7.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_7.setItemText(12, _translate("Form", "Русский язык"))
        self.class_7.setItemText(13, _translate("Form", "Технология"))
        self.class_7.setItemText(14, _translate("Form", "Физика"))
        self.class_7.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_7.setItemText(16, _translate("Form", "Химия"))
        self.class_8.setItemText(0, _translate("Form", "-"))
        self.class_8.setItemText(1, _translate("Form", "Алгебра"))
        self.class_8.setItemText(2, _translate("Form", "Английский язык"))
        self.class_8.setItemText(3, _translate("Form", "Биология"))
        self.class_8.setItemText(4, _translate("Form", "Вероятность и статистика"))
        self.class_8.setItemText(5, _translate("Form", "География"))
        self.class_8.setItemText(6, _translate("Form", "Геометрия"))
        self.class_8.setItemText(7, _translate("Form", "Информатика"))
        self.class_8.setItemText(8, _translate("Form", "История"))
        self.class_8.setItemText(9, _translate("Form", "Литература"))
        self.class_8.setItemText(10, _translate("Form", "Обществознание"))
        self.class_8.setItemText(11, _translate("Form", "ОБЖ"))
        self.class_8.setItemText(12, _translate("Form", "Русский язык"))
        self.class_8.setItemText(13, _translate("Form", "Технология"))
        self.class_8.setItemText(14, _translate("Form", "Физика"))
        self.class_8.setItemText(15, _translate("Form", "Физическая культура"))
        self.class_8.setItemText(16, _translate("Form", "Химия"))
